### ISSUE TITLE
Frequency Data Download

### ISSUE THREAD

**Issue by shalabhsuman** [babelomics/CSVS#8]
I was wondering if there is a way to download the population-specific VCF file(s) from the CIBERER Spanish Variant Server? I need information on “0Freq”, “1Freq” for MGP (267 healthy controls) and IBS (107 Spanish individuals from 1000genomes) sub-populations.

Shalabh

**Comment by agaor** [comment]
Hi Shalab, now there is a new save button at the bottom of the table with which you can download the search made.

**Comment by Dagsbio** [comment]
Hello, is there any way to download all variants and their frequencies of the 1582 unrelated Spanish individuals directly?

David.

**Comment by gemaroldan** [comment]
Hello David, in the new tab "Download" and with the "All" option you can download all the variants and their frequencies.

**Comment by Dagsbio** [comment]
Perfecto ya lo he conseguido, muchas gracias!
